### ISSUE TITLE
[ChannelTabs] Request: Server Name for Duplicate text channel names

### ISSUE THREAD

**Issue by XenoStone1009** [l0c4lh057/BetterDiscordStuff#48]
It gets confusing if you have 5 different General tabs open with no way to discern between them.

A simple Icon of the server the tab is in, or group/user if for some reason people want them to be all similar. Or have the server name then "- #channelname" after

**Comment by GE0NE** [comment]
This is sort of addressed by the addition of server icons in the latest release

**Comment by l0c4lh057** [comment]
Yes, that is why I added the icons (87aa75badf175e0b491d17d10d5090634c4a52a4). I won't add the guild name because that would take too much space, meaning you would either just see the guild name and not even (or only parts of) the channel name or you would have tab headers that are very wide which would look awful imo
