### ISSUE TITLE
[Account Switcher] Issue: alt left + 2 does that : ☻

### ISSUE THREAD

**Issue by KaKi87** [l0c4lh057/BetterDiscordStuff#5]
Hey,

_**Before you submit an issue please restart your discord. If the issue is still there feel free to write a bug report.**_
I did.

**Describe the bug**
- `left alt + 2` does that : `☻`
- middle click on avatar icon does that :

![2019-04-03 16_46_46-Settings](https://user-images.githubusercontent.com/21284089/55488916-33906c80-5631-11e9-9696-73c777dfd27d.png)

However, I set up 3 accounts.

**To Reproduce**
Set your tokens, master password and try to switch account

**Expected behavior**
Switch

**Screenshots**
Screenshot included.
No error nor any log showing while trying to switch, no matter the way I try.

**Information (please complete the following information):**
 - OS: Win10
 - Plugin Version: ` 1.0.3`  (latest)
 - Discord version: Stable
 - Compact Mode enabled? Nope

Thanks !

**Comment by l0c4lh057** [comment]
1. I don't really know what the problem is when you try to switch the account
2. If you only see one avatar when middle clicking the user icon but you have 3 accounts set, the plugin is not fetching your pfp. That should happen when you switch to the account using the plugin and then trigger the onSwitch event (change the channel or guild). I have a workaround (just show a blank image if a name is set) for that, I will push it in some time (still need to change some stuff).

**Comment by KaKi87** [comment]
Okay, thanks !
I think that the shortcut is overriden by Windows' alt codes shortcuts, which would explain why the event is not firing from the plugin.
Why not logging into the account while adding it in settings, which will allow you to fetch the profile picture immediately, but also show an error if the token is invalid ?

**Comment by l0c4lh057** [comment]
Oh I know what the issue is. You use the NumPad. If you use the numbers in the digit row it should work. I already tried registering the NumPad but that didn't work.

If I would login when you type in the token discord would reload like on a switch what would close the settings. Also, if the token is incorrect you just get redirected to the login screen and you do not see an error message.

**Comment by KaKi87** [comment]
Okay, switching between accounts without using numpad is working perfectly, and pretty fast, actually. It doesn't require to reload all the plugins, so it's very good.
However, I only see the two first accounts in the middle click tooltip, this tooltip and the switch modal are poorly styled, may I suggest displaying the accounts list in the `Ctrl + K` modal instead ?
Thanks :)

**Comment by l0c4lh057** [comment]
I am already working on a fix for the problem with the avatars not being fetched. that should happen when you switch to the account with the plugin and than trigger the onSwitch event (switch the guild or channel). only thing is some people wrote me that it is not happening for them, but i never had a problem with it. the update i will push soon has a workaround, it will just display an empty pfp but still show it, when you set a name for the account.

**Comment by KaKi87** [comment]
I mean I already switched to the third, and it isn't showing up.
What about my `Ctrl + K` idea ? :D

**Comment by l0c4lh057** [comment]
i'm sure i won't add that. you said that my menu is poorly styled, but when i add stuff to the menu i won't make a much fancier design. it will probably just get harder to make it good, bc themes can change everything and my menu currently adds stuff directly to discord's root element, so that should be safe.

**Comment by KaKi87** [comment]
The Ctrl + K menu is already styled, all you have to do is add HTML elements inside it.

**Comment by l0c4lh057** [comment]
nah, i cant just add the elements and assume everything will look good

**Comment by KaKi87** [comment]
Proof of concept
```js
{
	const separator = '<div style="width: 100%; height: 10px;"></div>';
	const tayne = document.querySelector('.da-quickswitcher .da-scroller');
	tayne.innerHTML += '<div class="resultDefault-1ymv3u result-oB0z-- da-resultDefault da-result"><div class="contentDefault-16dKSY content-1jxX5g da-contentDefault da-content"><div class="header-13MUnb da-header">Accounts</div></div></div>' + separator;
	[{
		tag: 'account1#9417',
		id: '136836513643651387'
	}, {
		tag: 'account2#8469',
		id: '897634138673513687'
	}, {
		tag: 'account3#2841',
		id: '722889213478921474'
	}].forEach(account => {
		tayne.innerHTML += `<div tabindex="${Math.max(...[...document.querySelectorAll('.da-quickswitcher .da-scroller *')].map(el => el.tabIndex)) + 1}" class="resultDefault-1ymv3u result-oB0z-- da-resultDefault da-result" role="button"><div class="contentUnread-3gTHvA content-1jxX5g da-contentUnread da-content"><div class="iconContainer-3UxHn2 da-iconContainer"></div><div class="name-2NBmhj da-name"><span class="match-38WbBN da-match">${account.tag}</span><span class="note-S--UP5 da-note">${account.id}</span></div></div></div>` + separator;
	});
}
```
All that's missing are the focus/over and click/enter events.
