### ISSUE TITLE
[PluginSettings] Issue: options don't turn on or off

### ISSUE THREAD

**Issue by ArcticWolfBtw** [l0c4lh057/BetterDiscordStuff#59]
Used to be able to turn settings on and off for the typing indicator, but it stopped working after there was a discord update yesterday.

**Expected behaviour**
Each of the toggles should turn on and off

![image](https://user-images.githubusercontent.com/55699401/96028971-e5793d80-0e51-11eb-9e72-922f390c915c.png)

as seen in the screenshot when i go to click the toggle, it just does that, and doesn't actually change state.

Windows
 - Plugin Version: 0.4.2
 - Discord version: Stable 69243 (445bd61)
 - Compact Mode enabled? no

**Comment by l0c4lh057** [comment]
this is something not happening in my plugins only. it seems like zlibrary is having this issue since some discord update. i cant do anything about it. fully close discord and edit the config file (is located next to the plugin file and is called `<PluginName>.config.js`), then open discord again. or just wait for zerebos to fix it in the library.
